const raw = window.DASHBOARD_DATA || [];
const clean = v => (v === null || v === undefined || v === '') ? '' : String(v).trim();
const label = v => clean(v) || 'Unassigned';
const number = v => { if(v === null || v === undefined || v === '') return 0; const n = Number(String(v).replace(/[$,% ,]/g,'')); return Number.isFinite(n) ? n : 0; };
const isParent = r => [1, '1', '1.0', true, 'true', 'TRUE', 'Yes', 'YES'].includes(r['Business Solution']) || number(r['Business Solution']) === 1;
const jira = r => label(r['Jira Status']);
const gto = r => label(r['GTO Work Category']).replace(/BAU-KTLO/i,'BAU/KTLO');
const isCompleted = r => /done|complete|completed|closed/i.test(jira(r)) || /done|complete|completed|closed/i.test(label(r['Workspace Status']));
const savings = r => Math.max(number(r['Total Savings/ Year']), number(r['Extended Savings ($/Year)']));
const users = r => number(r['# of Users Impacted']);
const typeSavings = r => label(r['Financial Impact']);
const summary = r => label(r['Summary']);
const money = v => v.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0});
const int = v => Math.round(v).toLocaleString();
function sum(arr, fn){return arr.reduce((a,r)=>a+fn(r),0)}
function by(arr, fn){return arr.reduce((a,r)=>{const k=fn(r);(a[k]??=[]).push(r);return a;},{})}
function unique(field){return [...new Set(raw.map(r=>clean(r[field])).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function populateFilters(){[['department','Department'],['jiraStatus','Jira Status'],['gtoCategory','GTO Work Category'],['savingType','Financial Impact']].forEach(([id,field])=>{const el=document.getElementById(id); unique(field).forEach(v=>{const opt=document.createElement('option'); opt.value=v; opt.textContent=v; el.appendChild(opt);});});}
function filtered(){const d=document.getElementById('department').value, j=document.getElementById('jiraStatus').value, g=document.getElementById('gtoCategory').value, s=document.getElementById('savingType').value, q=document.getElementById('search').value.toLowerCase();return raw.filter(r=>(!d||clean(r.Department)===d)&&(!j||clean(r['Jira Status'])===j)&&(!g||clean(r['GTO Work Category'])===g)&&(!s||clean(r['Financial Impact'])===s)&&(!q||JSON.stringify(r).toLowerCase().includes(q)));}
function renderCards(data){const parents=data.filter(isParent); const completeParents=parents.filter(isCompleted); const activeParents=parents.filter(r=>!isCompleted(r)); const cards=[['Parent initiatives',parents.length,int],['Total tickets',data.length,int],['Completed savings',sum(completeParents,savings),money],['Users impacted',sum(parents,users),int],['Backlog / active initiatives',activeParents.length,int]]; document.getElementById('cards').innerHTML=cards.map(([t,v,f])=>`<div class="card"><span>${t}</span><strong>${f(v)}</strong></div>`).join('');}
function palette(i){return ['#2f6f9f','#4c8fbd','#7ab1d1','#9bc5dd','#c2dbea','#6a8caf','#91a9c2','#b9c9d9'][i%8]}
function barChart(elId, rows, opts={}){const el=document.getElementById(elId); if(!rows.length){el.innerHTML='<div class="empty">No data for this selection.</div>';return;} const w=900, h=Math.max(opts.height||300, rows.length*(opts.rowHeight||34)+60), ml=opts.left||220, mr=120, mt=20, mb=36; const max=Math.max(...rows.map(r=>r.value),1); const chartW=w-ml-mr; let svg=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="xMinYMin meet">`; [0,.25,.5,.75,1].forEach(p=>{const x=ml+p*chartW; svg+=`<line class="gridline" x1="${x}" y1="${mt}" x2="${x}" y2="${h-mb}"/><text class="axisText" x="${x}" y="${h-12}" text-anchor="middle">${opts.money?money(max*p):int(max*p)}</text>`}); rows.forEach((r,i)=>{const y=mt+i*(opts.rowHeight||34)+6; const bw=(r.value/max)*chartW; svg+=`<text class="labelText" x="8" y="${y+16}">${escapeHtml(r.name).slice(0,42)}</text><rect class="bar" x="${ml}" y="${y}" width="${bw}" height="20" rx="6" fill="${palette(i)}"></rect><text class="valueText" x="${ml+bw+8}" y="${y+15}">${opts.money?money(r.value):int(r.value)}</text>`}); svg+='</svg>'; el.innerHTML=svg;}
function stackedBarChart(elId, statuses, cats, values){const el=document.getElementById(elId); if(!statuses.length){el.innerHTML='<div class="empty">No data for this selection.</div>';return;} const w=900,h=Math.max(320,statuses.length*44+90),ml=180,mr=70,mt=20,mb=70,chartW=w-ml-mr; const totals=statuses.map((s,i)=>cats.reduce((a,c,j)=>a+values[j][i],0)); const max=Math.max(...totals,1); let svg=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="xMinYMin meet">`; statuses.forEach((s,i)=>{let x=ml; const y=mt+i*42+6; svg+=`<text class="labelText" x="8" y="${y+17}">${escapeHtml(s).slice(0,28)}</text>`; cats.forEach((c,j)=>{const v=values[j][i]; const bw=(v/max)*chartW; if(v>0) svg+=`<rect x="${x}" y="${y}" width="${bw}" height="22" rx="5" fill="${palette(j)}"><title>${escapeHtml(c)}: ${v}</title></rect>`; x+=bw;}); svg+=`<text class="valueText" x="${ml+(totals[i]/max)*chartW+8}" y="${y+16}">${totals[i]}</text>`;}); svg+='</svg><div class="legend">'+cats.map((c,i)=>`<span><i class="swatch" style="background:${palette(i)}"></i>${escapeHtml(c)}</span>`).join('')+'</div>'; el.innerHTML=svg;}
function renderCharts(data){const catRows=Object.entries(by(data,gto)).map(([name,arr])=>({name,value:arr.length})).sort((a,b)=>b.value-a.value); barChart('categoryChart',catRows,{left:170}); const statuses=[...new Set(data.map(jira))].sort((a,b)=>a.localeCompare(b)); const cats=[...new Set(data.map(gto))].sort(); const vals=cats.map(c=>statuses.map(st=>data.filter(r=>gto(r)===c && jira(r)===st).length)); stackedBarChart('statusChart',statuses,cats,vals); const typeRows=Object.entries(by(data.filter(isParent),typeSavings)).map(([name,arr])=>({name,value:sum(arr,savings)})).filter(r=>r.value>0).sort((a,b)=>b.value-a.value); barChart('savingsTypeChart',typeRows,{left:270,money:true,rowHeight:38}); const userRows=Object.entries(by(data.filter(isParent),gto)).map(([name,arr])=>({name,value:sum(arr,users)})).sort((a,b)=>b.value-a.value); barChart('usersChart',userRows,{left:170});}
const cols=[{label:'Initiative',render:r=>`<strong>${escapeHtml(summary(r))}</strong><br><span class="pill">${escapeHtml(jira(r))}</span>`},{label:'Department',render:r=>escapeHtml(label(r.Department))},{label:'Sponsor',render:r=>escapeHtml(label(r['Executive Sponsor']))},{label:'Type of savings',render:r=>escapeHtml(typeSavings(r))},{label:'Users impacted',render:r=>int(users(r))},{label:'Annual savings',render:r=>`<span class="money">${money(savings(r))}</span>`}];
function table(id, cols, rows){document.getElementById(id).innerHTML='<thead><tr>'+cols.map(c=>`<th>${c.label}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${c.render(r)}</td>`).join('')+'</tr>').join('')+'</tbody>';}
function renderTables(data){const parents=data.filter(isParent); const top=parents.filter(r=>isCompleted(r)&&savings(r)>0).sort((a,b)=>savings(b)-savings(a)).slice(0,10); table('topSavings',cols,top); const backlog=parents.filter(r=>!isCompleted(r)).sort((a,b)=>jira(a).localeCompare(jira(b))||savings(b)-savings(a)); const groups=by(backlog,jira); document.getElementById('backlogGroups').innerHTML=Object.entries(groups).map(([status,rows])=>`<div class="group"><h3>${escapeHtml(status)} · ${rows.length} initiatives</h3><div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c.label}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c.render(r)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`).join('')||'<div class="empty">No backlog / active initiatives for this filter.</div>'; const detailCols=[{label:'Key',render:r=>escapeHtml(label(r['Jira Issue Key']))},{label:'Summary',render:r=>escapeHtml(summary(r))},{label:'GTO category',render:r=>escapeHtml(gto(r))},{label:'Jira status',render:r=>escapeHtml(jira(r))},{label:'Department',render:r=>escapeHtml(label(r.Department))},{label:'Users impacted',render:r=>int(users(r))},{label:'Savings',render:r=>money(savings(r))}]; table('detailTable',detailCols,data.slice(0,500));}
function refresh(){const data=filtered(); renderCards(data); renderCharts(data); renderTables(data);}
function exportCsv(){const data=filtered(); const headers=Object.keys(data[0]||{}); const csv=[headers.join(',')].concat(data.map(r=>headers.map(h=>`"${String(r[h]??'').replaceAll('"','""')}"`).join(','))).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download='gto_filtered_portfolio.csv'; a.click();}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]));}
populateFilters(); document.querySelectorAll('select,input').forEach(el=>el.addEventListener('input',refresh)); document.getElementById('exportCsv').addEventListener('click',exportCsv); refresh();
